DROP TABLE IF EXISTS times CASCADE;

CREATE TABLE times (
  id SERIAL PRIMARY KEY NOT NULL,
  event_id INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE,

  start_time TIMESTAMP NOT NULL,
  end_time TIMESTAMP NOT NULL,
  time_zone VARCHAR(10)
);
